{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-setuptools is now available for Red Hat Enterprise Linux 8.\n\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "The python-setuptools package provides a collection of enhancements to Python distribution utilities allowing convenient building and distribution of Python packages.\n\nSecurity Fix(es):\n\n* pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py (CVE-2022-40897)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat products and services.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2023:0835",
				"url": "https://access.redhat.com/errata/RHSA-2023:0835"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "2158559",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2158559"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2023/rhsa-2023_0835.json"
			}
		],
		"title": "Red Hat Security Advisory: python-setuptools security update",
		"tracking": {
			"current_release_date": "2024-11-06T02:29:57+00:00",
			"generator": {
				"date": "2024-11-06T02:29:57+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "4.1.1"
				}
			},
			"id": "RHSA-2023:0835",
			"initial_release_date": "2023-02-21T09:25:56+00:00",
			"revision_history": [
				{
					"date": "2023-02-21T09:25:56+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2023-02-21T09:25:56+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-11-06T02:29:57+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux BaseOS (v. 8)",
								"product": {
									"name": "Red Hat Enterprise Linux BaseOS (v. 8)",
									"product_id": "BaseOS-8.7.0.Z.MAIN",
									"product_identification_helper": {
										"cpe": "cpe:/o:redhat:enterprise_linux:8::baseos"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat Enterprise Linux"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch",
								"product": {
									"name": "platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch",
									"product_id": "platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/platform-python-setuptools@39.2.0-6.el8_7.1?arch=noarch"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python3-setuptools-0:39.2.0-6.el8_7.1.noarch",
								"product": {
									"name": "python3-setuptools-0:39.2.0-6.el8_7.1.noarch",
									"product_id": "python3-setuptools-0:39.2.0-6.el8_7.1.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-setuptools@39.2.0-6.el8_7.1?arch=noarch"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch",
								"product": {
									"name": "python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch",
									"product_id": "python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-setuptools-wheel@39.2.0-6.el8_7.1?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-setuptools-0:39.2.0-6.el8_7.1.src",
								"product": {
									"name": "python-setuptools-0:39.2.0-6.el8_7.1.src",
									"product_id": "python-setuptools-0:39.2.0-6.el8_7.1.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-setuptools@39.2.0-6.el8_7.1?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch as a component of Red Hat Enterprise Linux BaseOS (v. 8)",
					"product_id": "BaseOS-8.7.0.Z.MAIN:platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch"
				},
				"product_reference": "platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch",
				"relates_to_product_reference": "BaseOS-8.7.0.Z.MAIN"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-setuptools-0:39.2.0-6.el8_7.1.src as a component of Red Hat Enterprise Linux BaseOS (v. 8)",
					"product_id": "BaseOS-8.7.0.Z.MAIN:python-setuptools-0:39.2.0-6.el8_7.1.src"
				},
				"product_reference": "python-setuptools-0:39.2.0-6.el8_7.1.src",
				"relates_to_product_reference": "BaseOS-8.7.0.Z.MAIN"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-setuptools-0:39.2.0-6.el8_7.1.noarch as a component of Red Hat Enterprise Linux BaseOS (v. 8)",
					"product_id": "BaseOS-8.7.0.Z.MAIN:python3-setuptools-0:39.2.0-6.el8_7.1.noarch"
				},
				"product_reference": "python3-setuptools-0:39.2.0-6.el8_7.1.noarch",
				"relates_to_product_reference": "BaseOS-8.7.0.Z.MAIN"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch as a component of Red Hat Enterprise Linux BaseOS (v. 8)",
					"product_id": "BaseOS-8.7.0.Z.MAIN:python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch"
				},
				"product_reference": "python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch",
				"relates_to_product_reference": "BaseOS-8.7.0.Z.MAIN"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2022-40897",
			"cwe": {
				"id": "CWE-185",
				"name": "Incorrect Regular Expression"
			},
			"discovery_date": "2023-01-05T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2158559"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A flaw was found in Python Setuptools due to a regular expression Denial of Service (ReDoS) present in package_index.py. This issue could allow a remote attacker to cause a denial of service via HTML in a crafted package or custom PackageIndex page.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"BaseOS-8.7.0.Z.MAIN:platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch",
					"BaseOS-8.7.0.Z.MAIN:python-setuptools-0:39.2.0-6.el8_7.1.src",
					"BaseOS-8.7.0.Z.MAIN:python3-setuptools-0:39.2.0-6.el8_7.1.noarch",
					"BaseOS-8.7.0.Z.MAIN:python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2022-40897"
				},
				{
					"category": "external",
					"summary": "RHBZ#2158559",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2158559"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2022-40897",
					"url": "https://www.cve.org/CVERecord?id=CVE-2022-40897"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40897"
				},
				{
					"category": "external",
					"summary": "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
					"url": "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/"
				}
			],
			"release_date": "2022-12-22T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"BaseOS-8.7.0.Z.MAIN:platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch",
						"BaseOS-8.7.0.Z.MAIN:python-setuptools-0:39.2.0-6.el8_7.1.src",
						"BaseOS-8.7.0.Z.MAIN:python3-setuptools-0:39.2.0-6.el8_7.1.noarch",
						"BaseOS-8.7.0.Z.MAIN:python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2023:0835"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "HIGH",
						"attackVector": "NETWORK",
						"availabilityImpact": "HIGH",
						"baseScore": 5.9,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"BaseOS-8.7.0.Z.MAIN:platform-python-setuptools-0:39.2.0-6.el8_7.1.noarch",
						"BaseOS-8.7.0.Z.MAIN:python-setuptools-0:39.2.0-6.el8_7.1.src",
						"BaseOS-8.7.0.Z.MAIN:python3-setuptools-0:39.2.0-6.el8_7.1.noarch",
						"BaseOS-8.7.0.Z.MAIN:python3-setuptools-wheel-0:39.2.0-6.el8_7.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py"
		}
	]
}
