{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Updated mod_python packages that fix a denial of service vulnerability are\nnow available for Red Hat Linux.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "mod_python embeds the Python language interpreter within the Apache httpd\nserver.\n\nA bug has been found in mod_python versions 3.0.3 and earlier that can\nlead to a denial of service vulnerability.  The Common Vulnerabilities and\nExposures project (cve.mitre.org) has assigned the name CAN-2003-0973 to\nthis issue.\n\nAlthough Red Hat Linux 9 shipped with a version of mod_python\nthat contains this bug, our testing was unable to trigger the denial of\nservice vulnerability.  mod_python users are, however, advised to upgrade\nto these errata packages, which contain a backported patch that corrects\nthis bug.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat products and services.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2004:063",
				"url": "https://access.redhat.com/errata/RHSA-2004:063"
			},
			{
				"category": "external",
				"summary": "http://www.modpython.org/pipermail/mod_python/2003-November/014532.html",
				"url": "http://www.modpython.org/pipermail/mod_python/2003-November/014532.html"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2004/rhsa-2004_063.json"
			}
		],
		"title": "Red Hat Security Advisory: : Updated mod_python packages fix denial of service vulnerability",
		"tracking": {
			"current_release_date": "2024-11-21T22:57:39+00:00",
			"generator": {
				"date": "2024-11-21T22:57:39+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "4.2.1"
				}
			},
			"id": "RHSA-2004:063",
			"initial_release_date": "2004-02-26T07:36:00+00:00",
			"revision_history": [
				{
					"date": "2004-02-26T07:36:00+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2004-02-26T00:00:00+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-11-21T22:57:39+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat Linux 9",
								"product": {
									"name": "Red Hat Linux 9",
									"product_id": "Red Hat Linux 9",
									"product_identification_helper": {
										"cpe": "cpe:/o:redhat:linux:9"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat Linux"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2003-0973",
			"discovery_date": "",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1617112"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "Unknown vulnerability in mod_python 3.0.x before 3.0.4, and 2.7.x before 2.7.9, allows remote attackers to cause a denial of service (httpd crash) via a certain query string.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "security flaw",
					"title": "Vulnerability summary"
				}
			],
			"product_status": {
				"fixed": [
					"Red Hat Linux 9"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2003-0973"
				},
				{
					"category": "external",
					"summary": "RHBZ#1617112",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1617112"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2003-0973",
					"url": "https://www.cve.org/CVERecord?id=CVE-2003-0973"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2003-0973",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2003-0973"
				}
			],
			"release_date": "2003-11-28T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nTo update all RPMs for your particular architecture, run:\n\nrpm -Fvh [filenames]\n\nwhere [filenames] is a list of the RPMs you wish to upgrade.  Only those\nRPMs which are currently installed will be updated.  Those RPMs which are\nnot installed but included in the list will not be updated.  Note that you\ncan also use wildcards (*.rpm) if your current directory *only* contains the\ndesired RPMs.\n\nPlease note that this update is also available via Red Hat Network.  Many\npeople find this an easier way to apply updates.  To use Red Hat Network,\nlaunch the Red Hat Update Agent with the following command:\n\nup2date\n\nThis will start an interactive process that will result in the appropriate\nRPMs being upgraded on your system.\n\nIf up2date fails to connect to Red Hat Network due to SSL\nCertificate Errors, you need to install a version of the\nup2date client with an updated certificate.  The latest version of\nup2date is available from the Red Hat FTP site and may also be\ndownloaded directly from the RHN website:\n\nhttps://rhn.redhat.com/help/latest-up2date.pxt",
					"product_ids": [
						"Red Hat Linux 9"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2004:063"
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Low"
				}
			],
			"title": "security flaw"
		},
		{
			"cve": "CVE-2004-0096",
			"discovery_date": "2004-01-22T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "430510"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "Unknown vulnerability in mod_python 2.7.9 allows remote attackers to cause a denial of service (httpd crash) via a certain query string, a variant of CAN-2003-0973.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "mod_python remote DoS",
					"title": "Vulnerability summary"
				}
			],
			"product_status": {
				"fixed": [
					"Red Hat Linux 9"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2004-0096"
				},
				{
					"category": "external",
					"summary": "RHBZ#430510",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=430510"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2004-0096",
					"url": "https://www.cve.org/CVERecord?id=CVE-2004-0096"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2004-0096",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2004-0096"
				}
			],
			"release_date": "2004-01-22T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nTo update all RPMs for your particular architecture, run:\n\nrpm -Fvh [filenames]\n\nwhere [filenames] is a list of the RPMs you wish to upgrade.  Only those\nRPMs which are currently installed will be updated.  Those RPMs which are\nnot installed but included in the list will not be updated.  Note that you\ncan also use wildcards (*.rpm) if your current directory *only* contains the\ndesired RPMs.\n\nPlease note that this update is also available via Red Hat Network.  Many\npeople find this an easier way to apply updates.  To use Red Hat Network,\nlaunch the Red Hat Update Agent with the following command:\n\nup2date\n\nThis will start an interactive process that will result in the appropriate\nRPMs being upgraded on your system.\n\nIf up2date fails to connect to Red Hat Network due to SSL\nCertificate Errors, you need to install a version of the\nup2date client with an updated certificate.  The latest version of\nup2date is available from the Red Hat FTP site and may also be\ndownloaded directly from the RHN website:\n\nhttps://rhn.redhat.com/help/latest-up2date.pxt",
					"product_ids": [
						"Red Hat Linux 9"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2004:063"
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "mod_python remote DoS"
		}
	]
}
