{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Updated python-django packages that fix two security issues are now\navailable for Red Hat OpenStack 3.0.\n\nThe Red Hat Security Response Team has rated this update as having moderate\nsecurity impact. A Common Vulnerability Scoring System (CVSS) base score,\nwhich gives a detailed severity rating, is available from the CVE link in\nthe References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "Django is a high-level Python Web framework that encourages rapid\ndevelopment and a clean, pragmatic design. It focuses on automating as much\nas possible and adhering to the DRY (Don't Repeat Yourself) principle.\n\nIt was discovered that the django.utils.http.is_safe_url() function\nconsidered any URL that used a scheme other than HTTP or HTTPS (for\nexample, \"javascript:\") as safe. An attacker could potentially use this\nflaw to perform cross-site scripting (XSS) attacks. (CVE-2013-6044)\n\nA directory traversal flaw was found in Django's \"ssi\" template tag, which\ntakes a file path as input and outputs that file's contents. An attacker\nable to alter templates that made use of the \"ssi\" tag on a site could use\nthis flaw to access any local files accessible to Django. (CVE-2013-4315)\n\nRed Hat would like to thank James Bennett of Django for reporting\nCVE-2013-4315.\n\nAll python-django users are advised to upgrade to these updated packages,\nwhich contain a backported patch to correct these issues.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat products and services.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2013:1521",
				"url": "https://access.redhat.com/errata/RHSA-2013:1521"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "1004969",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1004969"
			},
			{
				"category": "external",
				"summary": "1016394",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1016394"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2013/rhsa-2013_1521.json"
			}
		],
		"title": "Red Hat Security Advisory: python-django security update",
		"tracking": {
			"current_release_date": "2024-11-05T18:14:54+00:00",
			"generator": {
				"date": "2024-11-05T18:14:54+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "4.1.1"
				}
			},
			"id": "RHSA-2013:1521",
			"initial_release_date": "2013-11-14T17:25:00+00:00",
			"revision_history": [
				{
					"date": "2013-11-14T17:25:00+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2013-11-14T17:29:40+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-11-05T18:14:54+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat Enterprise Linux OpenStack Platform 3.0",
								"product": {
									"name": "Red Hat Enterprise Linux OpenStack Platform 3.0",
									"product_id": "6Server-Grizzly",
									"product_identification_helper": {
										"cpe": "cpe:/a:redhat:openstack:3::el6"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat OpenStack Platform"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "Django14-doc-0:1.4.8-1.el6ost.noarch",
								"product": {
									"name": "Django14-doc-0:1.4.8-1.el6ost.noarch",
									"product_id": "Django14-doc-0:1.4.8-1.el6ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/Django14-doc@1.4.8-1.el6ost?arch=noarch"
									}
								}
							},
							{
								"category": "product_version",
								"name": "Django14-0:1.4.8-1.el6ost.noarch",
								"product": {
									"name": "Django14-0:1.4.8-1.el6ost.noarch",
									"product_id": "Django14-0:1.4.8-1.el6ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/Django14@1.4.8-1.el6ost?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "Django14-0:1.4.8-1.el6ost.src",
								"product": {
									"name": "Django14-0:1.4.8-1.el6ost.src",
									"product_id": "Django14-0:1.4.8-1.el6ost.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/Django14@1.4.8-1.el6ost?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "Django14-0:1.4.8-1.el6ost.noarch as a component of Red Hat Enterprise Linux OpenStack Platform 3.0",
					"product_id": "6Server-Grizzly:Django14-0:1.4.8-1.el6ost.noarch"
				},
				"product_reference": "Django14-0:1.4.8-1.el6ost.noarch",
				"relates_to_product_reference": "6Server-Grizzly"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "Django14-0:1.4.8-1.el6ost.src as a component of Red Hat Enterprise Linux OpenStack Platform 3.0",
					"product_id": "6Server-Grizzly:Django14-0:1.4.8-1.el6ost.src"
				},
				"product_reference": "Django14-0:1.4.8-1.el6ost.src",
				"relates_to_product_reference": "6Server-Grizzly"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "Django14-doc-0:1.4.8-1.el6ost.noarch as a component of Red Hat Enterprise Linux OpenStack Platform 3.0",
					"product_id": "6Server-Grizzly:Django14-doc-0:1.4.8-1.el6ost.noarch"
				},
				"product_reference": "Django14-doc-0:1.4.8-1.el6ost.noarch",
				"relates_to_product_reference": "6Server-Grizzly"
			}
		]
	},
	"vulnerabilities": [
		{
			"acknowledgments": [
				{
					"names": [
						"James Bennett"
					],
					"organization": "Django"
				}
			],
			"cve": "CVE-2013-4315",
			"cwe": {
				"id": "CWE-22",
				"name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
			},
			"discovery_date": "2013-09-03T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1004969"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "Directory traversal vulnerability in Django 1.4.x before 1.4.7, 1.5.x before 1.5.3, and 1.6.x before 1.6 beta 3 allows remote attackers to read arbitrary files via a file path in the ALLOWED_INCLUDE_ROOTS setting followed by a .. (dot dot) in a ssi template tag.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-django: directory traversal with \"ssi\" template tag",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.noarch",
					"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.src",
					"6Server-Grizzly:Django14-doc-0:1.4.8-1.el6ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2013-4315"
				},
				{
					"category": "external",
					"summary": "RHBZ#1004969",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1004969"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2013-4315",
					"url": "https://www.cve.org/CVERecord?id=CVE-2013-4315"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2013-4315",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2013-4315"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2013/sep/10/security-releases-issued/",
					"url": "https://www.djangoproject.com/weblog/2013/sep/10/security-releases-issued/"
				}
			],
			"release_date": "2013-09-10T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/site/articles/11258",
					"product_ids": [
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.noarch",
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.src",
						"6Server-Grizzly:Django14-doc-0:1.4.8-1.el6ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2013:1521"
				}
			],
			"scores": [
				{
					"cvss_v2": {
						"accessComplexity": "HIGH",
						"accessVector": "NETWORK",
						"authentication": "SINGLE",
						"availabilityImpact": "NONE",
						"baseScore": 2.1,
						"confidentialityImpact": "PARTIAL",
						"integrityImpact": "NONE",
						"vectorString": "AV:N/AC:H/Au:S/C:P/I:N/A:N",
						"version": "2.0"
					},
					"products": [
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.noarch",
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.src",
						"6Server-Grizzly:Django14-doc-0:1.4.8-1.el6ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Low"
				}
			],
			"title": "python-django: directory traversal with \"ssi\" template tag"
		},
		{
			"cve": "CVE-2013-6044",
			"cwe": {
				"id": "CWE-79",
				"name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
			},
			"discovery_date": "2013-10-08T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1016394"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "The is_safe_url function in utils/http.py in Django 1.4.x before 1.4.6, 1.5.x before 1.5.2, and 1.6 before beta 2 treats a URL's scheme as safe even if it is not HTTP or HTTPS, which might introduce cross-site scripting (XSS) or other vulnerabilities into Django applications that use this function, as demonstrated by \"the login view in django.contrib.auth.views\" and the javascript: scheme.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-django: xss in is_safe_url function",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.noarch",
					"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.src",
					"6Server-Grizzly:Django14-doc-0:1.4.8-1.el6ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2013-6044"
				},
				{
					"category": "external",
					"summary": "RHBZ#1016394",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1016394"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2013-6044",
					"url": "https://www.cve.org/CVERecord?id=CVE-2013-6044"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2013-6044",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2013-6044"
				}
			],
			"release_date": "2013-08-14T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/site/articles/11258",
					"product_ids": [
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.noarch",
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.src",
						"6Server-Grizzly:Django14-doc-0:1.4.8-1.el6ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2013:1521"
				}
			],
			"scores": [
				{
					"cvss_v2": {
						"accessComplexity": "MEDIUM",
						"accessVector": "NETWORK",
						"authentication": "NONE",
						"availabilityImpact": "NONE",
						"baseScore": 4.3,
						"confidentialityImpact": "NONE",
						"integrityImpact": "PARTIAL",
						"vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
						"version": "2.0"
					},
					"products": [
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.noarch",
						"6Server-Grizzly:Django14-0:1.4.8-1.el6ost.src",
						"6Server-Grizzly:Django14-doc-0:1.4.8-1.el6ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "python-django: xss in is_safe_url function"
		}
	]
}
